version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: your-db-host
      DB_NAME: your-db-name
      DB_USER: your-db-user
      DB_PASS: your-db-password
      S3_BUCKET: your-s3-bucket